spring:
  data:
    mongodb:
      uri: ${MONGODB_URL}
    redis:
      host: localhost
      port: 6379
  application:
    name: user-service

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000


server:
  port: 8081

